In [1]:
import pandas as pd
import numpy as np

In [2]:
songs = pd.read_csv('bolly_songs.csv', encoding = 'cp1252')

In [3]:
songs.head()

,Song-Id,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,1,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,8.8
1,2,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,9.0
2,3,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,9.7
3,4,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,9.1
4,5,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,9.2

In [4]:
songs.shape

(2419, 6)

In [5]:
songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2419 entries, 0 to 2418
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Song-Id         2419 non-null   int64
 1   Song-Name       2419 non-null   object
 2   Singer/Artists  2409 non-null   object
 3   Genre           2419 non-null   object
 4   Album/Movie     2416 non-null   object
 5   User-Rating     2419 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 113.5+ KB

In [6]:
songs.isnull().sum()

Song-Id            0
Song-Name          0
Singer/Artists    10
Genre              0
Album/Movie        3
User-Rating        0
dtype: int64

In [7]:
songs[songs['Singer/Artists'].isnull() | songs['Album/Movie'].isnull()]

,Song-Id,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
366,369,Kya Khoob Lagti Ho,NaN,BollywoodDance,Dharmatma,8.6
618,621,Jag Soona Soona Lage,NaN,BollywoodSad,Om Shanti Om,9.4
859,862,Tu Hi Re,Hariharan,BollywoodRomantic,NaN,9.4
954,957,Dhoom 3 Mashup,NaN,BollywoodDance,Dhoom 3,8.1
1281,1284,Jazba,Shilpa Rao,BollywoodDance,NaN,9.4
1315,1318,Aur Kya,Abhijeet,BollywoodDanceRomance,NaN,9.5
1322,1325,Ghar Aaja Pardesi,NaN,BollywoodDance,Dilwale Dulhania Le Jayenge,8.5
1746,1749,Pyar Chahiye Mujhe Jine Ke Liye,NaN,BollywoodRomantic,Manokaamnaa,9.1
1865,1868,Tu Koi Aur Hai,NaN,BollywoodSad,Tamasha,9.5
2032,2035,Tandav,NaN,BollywoodDance,Chaalbaaz,9.3
2086,2089,Chaar Botal Vodka (Remix),NaN,BollywoodDance,Ragini MMS 2,9.3
2095,2098,O Basanti Pavan,NaN,BollywoodDance,Jis Desh Mein Ganga Behti Hai,8.7
2366,2369,Tanki (Bhaven Version),NaN,BollywoodDance,Youngistaan,7.5

In [8]:
songs.dropna(inplace = True)

In [9]:
songs.isnull().sum()

Song-Id           0
Song-Name         0
Singer/Artists    0
Genre             0
Album/Movie       0
User-Rating       0
dtype: int64

In [10]:
songs.shape

(2406, 6)

In [11]:
songs.columns

Index(['Song-Id', 'Song-Name', 'Singer/Artists', 'Genre', 'Album/Movie',
       'User-Rating'],
      dtype='object')

In [12]:
songs.rename(columns = {'Song-Id' : 'id',
                        'Song-Name' : 'song',
                        'Singer/Artists' : 'artist',
                        'Genre' : 'genre',
                        'Album/Movie' : 'movie',
                        'User-Rating' : 'rating'}, inplace = True)

In [13]:
songs.head()

,id,song,artist,genre,movie,rating
0,1,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,8.8
1,2,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,9.0
2,3,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,9.7
3,4,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,9.1
4,5,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,9.2

In [14]:
songs.duplicated().sum()

0

In [15]:
songs['artist'] = songs['artist'].apply(lambda x : x.split(','))
songs['artist']

0                 [Kumar Sanu,  Mika Singh,  Neha Kakkar]
1                             [Neha Kakkar,  Tony Kakkar]
2                                         [Ranveer Singh]
3               [Jyotica Tangri,  Shaan,  Subhro Ganguly]
4       [Asees Kaur,  Rahat Fateh Ali Khan,  Tanishk B...
                              ...
2414                                    [Lata Mangeshkar]
2415                    [Lata Mangeshkar,  Suresh Wadkar]
2416                                        [Jagjit Kaur]
2417                                        [Asha Bhosle]
2418                                    [Lata Mangeshkar]
Name: artist, Length: 2406, dtype: object

In [16]:
songs['artist'] = songs['artist'].apply(lambda x : [i.replace(' ', '') for i in x])
songs['artist']

0                  [KumarSanu, MikaSingh, NehaKakkar]
1                            [NehaKakkar, TonyKakkar]
2                                      [RanveerSingh]
3               [JyoticaTangri, Shaan, SubhroGanguly]
4       [AseesKaur, RahatFatehAliKhan, TanishkBagchi]
                            ...
2414                                 [LataMangeshkar]
2415                   [LataMangeshkar, SureshWadkar]
2416                                     [JagjitKaur]
2417                                     [AshaBhosle]
2418                                 [LataMangeshkar]
Name: artist, Length: 2406, dtype: object

In [17]:
songs['genre'] = songs['genre'].apply(lambda x : x.split())
songs['genre']

0               [BollywoodDance]
1       [BollywoodDanceRomantic]
2               [BollywoodDance]
3               [BollywoodDance]
4            [BollywoodRomantic]
                  ...
2414            [BollywoodDance]
2415            [BollywoodDance]
2416            [BollywoodDance]
2417            [BollywoodDance]
2418         [BollywoodRomantic]
Name: genre, Length: 2406, dtype: object

In [18]:
songs['movie'] = songs['movie'].apply(lambda x : x.replace(' ', ''))
songs['movie']

0                     Simmba
1                 LukaChuppi
2                   GullyBoy
3               TotalDhamaal
4                     Simmba
                ...
2414    JabPyarKisiSeHotaHai
2415                   Lamhe
2416         SholaAurShabnam
2417         SholaAurShabnam
2418               WoKaunThi
Name: movie, Length: 2406, dtype: object

In [19]:
songs['movie'] = songs['movie'].apply(lambda x : x.split())
songs['movie']

0                     [Simmba]
1                 [LukaChuppi]
2                   [GullyBoy]
3               [TotalDhamaal]
4                     [Simmba]
                 ...
2414    [JabPyarKisiSeHotaHai]
2415                   [Lamhe]
2416         [SholaAurShabnam]
2417         [SholaAurShabnam]
2418               [WoKaunThi]
Name: movie, Length: 2406, dtype: object

In [20]:
songs['rating'] = songs['rating'].astype('str').apply(lambda x : x.split())
songs['rating']

0       [8.8]
1       [9.0]
2       [9.7]
3       [9.1]
4       [9.2]
        ...
2414    [8.7]
2415    [8.1]
2416    [7.2]
2417    [6.6]
2418    [9.9]
Name: rating, Length: 2406, dtype: object

In [21]:
songs['tags'] = songs['artist'] + songs['genre'] + songs['movie'] + songs['rating']

In [22]:
songs.head()

,id,song,artist,genre,movie,rating,tags
0,1,Aankh Marey,"[KumarSanu, MikaSingh, NehaKakkar]",[BollywoodDance],[Simmba],[8.8],"[KumarSanu, MikaSingh, NehaKakkar, BollywoodDa..."
1,2,Coca Cola,"[NehaKakkar, TonyKakkar]",[BollywoodDanceRomantic],[LukaChuppi],[9.0],"[NehaKakkar, TonyKakkar, BollywoodDanceRomanti..."
2,3,Apna Time Aayega,[RanveerSingh],[BollywoodDance],[GullyBoy],[9.7],"[RanveerSingh, BollywoodDance, GullyBoy, 9.7]"
3,4,Mungda,"[JyoticaTangri, Shaan, SubhroGanguly]",[BollywoodDance],[TotalDhamaal],[9.1],"[JyoticaTangri, Shaan, SubhroGanguly, Bollywoo..."
4,5,Tere Bin,"[AseesKaur, RahatFatehAliKhan, TanishkBagchi]",[BollywoodRomantic],[Simmba],[9.2],"[AseesKaur, RahatFatehAliKhan, TanishkBagchi, ..."

In [23]:
new_df = songs[['id', 'song', 'tags']]
new_df.head()

   id              song                                               tags
0   1       Aankh Marey  [KumarSanu, MikaSingh, NehaKakkar, BollywoodDa...
1   2         Coca Cola  [NehaKakkar, TonyKakkar, BollywoodDanceRomanti...
2   3  Apna Time Aayega      [RanveerSingh, BollywoodDance, GullyBoy, 9.7]
3   4            Mungda  [JyoticaTangri, Shaan, SubhroGanguly, Bollywoo...
4   5          Tere Bin  [AseesKaur, RahatFatehAliKhan, TanishkBagchi, ...

In [24]:
new_df['tags'] = new_df['tags'].apply(lambda x : ' '.join(x))
new_df.head()

C:\Users\dell\AppData\Local\Temp\ipykernel_10984\558971744.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : ' '.join(x))

   id              song                                               tags
0   1       Aankh Marey  KumarSanu MikaSingh NehaKakkar BollywoodDance ...
1   2         Coca Cola  NehaKakkar TonyKakkar BollywoodDanceRomantic L...
2   3  Apna Time Aayega           RanveerSingh BollywoodDance GullyBoy 9.7
3   4            Mungda  JyoticaTangri Shaan SubhroGanguly BollywoodDan...
4   5          Tere Bin  AseesKaur RahatFatehAliKhan TanishkBagchi Boll...

In [25]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())
new_df.head()

C:\Users\dell\AppData\Local\Temp\ipykernel_10984\657974225.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

   id              song                                               tags
0   1       Aankh Marey  kumarsanu mikasingh nehakakkar bollywooddance ...
1   2         Coca Cola  nehakakkar tonykakkar bollywooddanceromantic l...
2   3  Apna Time Aayega           ranveersingh bollywooddance gullyboy 9.7
3   4            Mungda  jyoticatangri shaan subhroganguly bollywooddan...
4   5          Tere Bin  aseeskaur rahatfatehalikhan tanishkbagchi boll...

In [26]:
new_df.reset_index(inplace = True)
new_df.drop(columns = ['index'], inplace = True)
new_df.head()

C:\Users\dell\AppData\Local\Temp\ipykernel_10984\2357451114.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop(columns = ['index'], inplace = True)

   id              song                                               tags
0   1       Aankh Marey  kumarsanu mikasingh nehakakkar bollywooddance ...
1   2         Coca Cola  nehakakkar tonykakkar bollywooddanceromantic l...
2   3  Apna Time Aayega           ranveersingh bollywooddance gullyboy 9.7
3   4            Mungda  jyoticatangri shaan subhroganguly bollywooddan...
4   5          Tere Bin  aseeskaur rahatfatehalikhan tanishkbagchi boll...

In [27]:
new_df.tail()

,id,song,tags
2401,2417,Tum Jaise Bigde Babu Se,latamangeshkar bollywooddance jabpyarkisisehot...
2402,2418,O Yaad Nahi Bhool Gaya,latamangeshkar sureshwadkar bollywooddance lam...
2403,2419,Ladi Re Ladi Tujhse Aankh Jo Ladi,jagjitkaur bollywooddance sholaaurshabnam 7.2
2404,2420,Mummy Aur Daddy Mein Ladai Ho Gayi,ashabhosle bollywooddance sholaaurshabnam 6.6
2405,2421,Lag Ja Gale,latamangeshkar bollywoodromantic wokaunthi 9.9

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 5000)

In [29]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [30]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
vectors.shape

(2406, 1697)

In [32]:
cv.get_feature_names()

C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['13',
 '1920',
 '1921',
 '1947',
 '2states',
 '3dev',
 '3idiots',
 '3storeys',
 '55',
 '7ekterasaath',
 '7khoonmaaf',
 '7welcometolondon',
 '9211',
 'aadesh',
 'aagalelagjaa',
 'aah',
 'aajamerijaan',
 'aajanachle',
 'aakankshasharma',
 'aakhirkyon',
 'aakhreeraasta',
 'aamantrikha',
 'aamir',
 'aan',
 'aanchalsethi',
 'aandhi',
 'aaniya',
 'aankhen',
 'aapkaasurroor',
 'aapkikasam',
 'aapkikhatir',
 'aapsemausiiquii',
 'aaryandineshkanagaratnam',
 'aashayein',
 'aashiqbanayaaapne',
 'aashiqui',
 'aashiqui2',
 'aashqui2',
 'aaskapanchhi',
 'aasthagill',
 'aazaan',
 'abcd',
 'abcd2',
 'abhaydeol',
 'abhayjodhpurkar',
 'abhijeet',
 'abhijeetsawant',
 'abhijitvaghani',
 'abhimaan',
 'abhisheknailwal',
 'abhisheknehwal',
 'actionjackson',
 'actionreplayy',
 'actorinlaw',
 'aditipaul',
 'aditisinghsharma',
 'aditsinghsharma',
 'adityan',
 'adityanarayan',
 'adnansami',
 'aedilhaimushkil',
 'aflyingjatt',
 'agentleman',
 'agentvinod',
 'agneepath',
 'ahmedhussain',
 'airlift',
 'aisha',
 'aishwarya',
 'aishwaryabhandari',
 'aishwaryamajmudar',
 'aishwaryanigam',
 'aitraaz',
 'aiyaary',
 'aiyyaa',
 'ajabgazabblove',
 'ajabpremkighazabkahani',
 'ajay',
 'ajaygogavale',
 'ajnabee',
 'akankshabhandari',
 'akasasingh',
 'akashojha',
 'akelehumakeletum',
 'akhilsachdeva',
 'akhtarchanalzahri',
 'akira',
 'akon',
 'akritikakar',
 'aksar',
 'aksar2',
 'akshatadixit',
 'alamgirkhan',
 'alfaaz',
 'alishachinai',
 'alishachinoy',
 'alizafar',
 'alizehashking',
 'alkayadnik',
 'alkayagik',
 'alkayagnik',
 'alliswell',
 'allthebest',
 'alone',
 'altamasfaridi',
 'altamashfaridi',
 'altamashkhan',
 'alwayskabhikabhi',
 'alyssamendonsa',
 'amaalmallik',
 'amantrikha',
 'amarakbaranthony',
 'amararshi',
 'amimishra',
 'amirjamal',
 'amit',
 'amitabhbachchan',
 'amitabhbhattacharya',
 'amitgupta',
 'amitkumar',
 'amitmishra',
 'amitsana',
 'amittrivedi',
 'amjadfaridsabri',
 'ammyvirk',
 'amritakak',
 'amritasingh',
 'anand',
 'anandkumarc',
 'anandraajanand',
 'ananyawadkar',
 'anari',
 'andaaz',
 'andazapnaapna',
 'andhadhun',
 'andmrs',
 'anitagandharva',
 'anjaam',
 'anjaan',
 'anjaanaanjaani',
 'anjjan',
 'ankittiwari',
 'anmolmalik',
 'anpadh',
 'antara',
 'antaramitra',
 'anugrah',
 'anumalik',
 'anupamadeshpande',
 'anupamamod',
 'anupghoshal',
 'anupjalota',
 'anuradha',
 'anuradhapaudwal',
 'anuradhasriram',
 'anushamani',
 'anushkamanchanda',
 'anushkashahaney',
 'anwar',
 'anweshaa',
 'anwesshaa',
 'anybodycandance',
 'aparnaabhaagwat',
 'apekshadandekar',
 'aradhana',
 'arijitsingh',
 'arjun',
 'arjunpandit',
 'arko',
 'armaanmalik',
 'arnabdutta',
 'aroh',
 'arpan',
 'arpitamukherjee',
 'arshadwarsi',
 'arth',
 'arun',
 'arunbakshi',
 'aruningle',
 'aryaacharya',
 'asadbhopali',
 'aseeskaur',
 'ashabhosle',
 'ashimamahajan',
 'ashishpandit',
 'ashking',
 'ashoka',
 'ashwin',
 'asittripathy',
 'aslinaqli',
 'asoka',
 'atifaslam',
 'atithitumkabjaoge',
 'atul',
 'atulkale',
 'aurielcordo',
 'awaara',
 'awarapan',
 'awesomemausam',
 'ayasawanjhoomke',
 'ayouthfuljoyride',
 'ayub',
 'ayushmankhurana',
 'ayushmannkhurrana',
 'azam',
 'azhar',
 'baabaaablacksheep',
 'baabaablacksheep',
 'baadshah',
 'baadshaho',
 'baaghi',
 'baaghi2',
 'baahubali2',
 'baarbaardekho',
 'baazaar',
 'baazigar',
 'babbumaan',
 'babuhaabi',
 'babulsupriyo',
 'baby',
 'babyaparna',
 'babysneha',
 'bachnaaehaseeno',
 'bademiyanchotemiyan',
 'badhaaiho',
 'badlapur',
 'badmaashcompany',
 'badrinathkidulhania',
 'badshah',
 'baghban',
 'bahubali',
 'bajateyraho',
 'bajiraomastani',
 'bajrangibhaijaan',
 'balasubrahmanyam',
 'balasubramanyam',
 'balibrahambhatt',
 'balibrahmbhatt',
 'bandbaajabaaraat',
 'bandini',
 'bandofpower',
 'bangbang',
 'banjyotsna',
 'bappilahiri',
 'bareillykibafi',
 'bareillykibarfi',
 'barfi',
 'barkhaa',
 'barsaat',
 'basavalingaiahhiremath',
 'basekpal',
 'battigulmeterchalu',
 'beessaalbaad',
 'befikre',
 'begumjaan',
 'behenhogiteri',
 'beiimaanlove',
 'bela',
 'belashende',
 'belasulakhe',
 'bennydayal',
 'besharam',
 'beta',
 'bewafaa',
 'bewaffa',
 'bewakoofiaan',
 'bewakoofiyaan',
 'bewakoofiyan',
 'bhaagjohnny',
 'bhaagmilkhabhaag',
 'bhaiajisuperhit',
 'bhanupratap',
 'bhaveshjoshisuperhero',
 'bhavyapandit',
 'bhoolbhulaiyaa',
 'bhoomi',
 'bhoomitrivedi',
 'bhoothnath',
 'bhoothnathreturns',
 'bhopalexpress',
 'bhupindersingh',
 'biancagomes',
 'bilalsaeed',
 'billu',
 'biwino',
 'blaaze',
 'black',
 'blackmail',
 'blue',
 'bob',
 'bobbyjasoos',
 'bodyguard',
 'bol',
 'bollywood',
 'bollywooddance',
 'bollywooddancemotivationalpatriotic',
 'bollywooddancepatriotic',
 'bollywooddanceromantic',
 'bollywooddancesad',
 'bollywooddancesensual',
 'bollywooddevotional',
 'bollywooddevotionalsad',
 'bollywoodheightsmilengemilenge',
 'bollywoodheightsmileynaamileyhum',
 'bollywoodmotivational',
 'bollywoodmotivationalpatriotic',
 'bollywoodpatriotic',
 'bollywoodpatrioticsad',
 'bollywoodromance',
 'bollywoodromantic',
 'bollywoodromanticsad',
 'bollywoodromanticsadsensual',
 'bollywoodromanticsensual',
 'bollywoodsad',
 'bollywoodsensual',
 'bombayjayashri',
 'border',
 'boss',
 'bpraak',
 'breakupkebaad',
 'brigitteyaghi',
 'brijeshshandaliya',
 'brijeshshandilya',
 'brothers',
 'bullettraja',
 'buntyaurbabli',
 'burman',
 'caralisamonteiro',
 'caravaan',
 'chaalbaaz',
 'chakdeindia',
 'chakjawana',
 'challodriver',
 'chaltechalte',
 'chamatkar',
 'chameli',
 'chancepedance',
 'chandni',
 'chandnichowktochina',
 'chashmebaddoor',
 'chaudhvinkachand',
 'cheatindia',
 'chef',
 'chennaiexpress',
 'chhalia',
 'chinmaye',
 'chinmayisripaada',
 'chithra',
 'chitrasingh',
 'chorichorichupkechupke',
 'chorus',
 'chupchupke',
 'citylights',
 'clintoncerejo',
 'cocktail',
 'commando2',
 'coolie',
 'coolieno',
 'creature3d',
 'crook',
 'cruz',
 'cruzaiman',
 'cucaroseta',
 'daasdev',
 'daawateishq',
 'dabangg',
 'dabangg2',
 'dabboomalik',
 'daddycool',
 'dalermehndi',
 'damini',
 'dangal',
 'dangerousishq',
 'danishsabri',
 'daretolove',
 'darlingdarling',
 'darr',
 'darshana',
 'darshanraval',
 'davidklyton',
 'dayavan',
 'daysoftafree',
 'dcerejo',
 'dearzindagi',
 'debojitsaha',
 'dedanadan',
 'dedhishqiya',
 'deepali',
 'deepalisathe',
 'deepmoney',
 'deewaar',
 'deewane',
 'delhi',
 'desiboyz',
 'dev',
 'devd',
 'devdas',
 'devisriprasad',
 'devkipandit',
 'devnegi',
 'dhadak',
 'dhadkan',
 'dhamaal',
 'dhamal',
 'dhanak',
 'dharamkaram',
 'dharamveer',
 'dharmatma',
 'dhatteriki',
 'dheeredheere',
 'dhoni',
 'dhoom',
 'dhoom2',
 'dhoom3',
 'dhvanibhanushali',
 'dil',
 'dilapnaaurpreetparai',
 'dilbolehadippa',
 'dilchahtahai',
 'dildhadaknedo',
 'dildiyahai',
 'dilhaikemantanahin',
 'dilhaitumhaara',
 'diljale',
 'diljitdosanjh',
 'diljonakehsaka',
 'diljuunglee',
 'dilkabaddi',
 'dilkarishta',
 'dilkyakare',
 'dilliwaalizaalimgirlfriend',
 'dilmaangemore',
 'dilse',
 'dilshad',
 'dilteradeewana',
 'diltohbachhahai',
 'diltohpagalhai',
 'diltopagalhai',
 'dilwale',
 'dilwaledulhanialejayenge',
 'dipanshupandit',
 'discodancer',
 'dishasharma',
 'dishoom',
 'diva',
 'divyakumar',
 'dokaliyan',
 'dolafzonkikahani',
 'dollykidoli',
 'dominique',
 'dominiquecrezo',
 'don',
 'dostana',
 'doubledhammal',
 'dulhamilgaya',
 'dulhanhumlejaayenge',
 'dulhanhumlejayenge',
 'dulheraja',
 'dum',
 'dumlagakehaisha',
 'dummaarodum',
 'dus',
 'dushman',
 'earl',
 'earld',
 'earledgar',
 'earth',
 'ehsaannoorani',
 'ekkeestopponkisalaami',
 'ekladkikodekhatohaisalaga',
 'ekmusafirekhasina',
 'ekpahelileela',
 'ekrishtaa',
 'ekthatiger',
 'ekvillain',
 'enbee',
 'evilreturns',
 'falakshabir',
 'falgunipathak',
 'fanaa',
 'fanneykhan',
 'faraar',
 'farhanakhtar',
 'farhansabri',
 'farhansaeed',
 'farhid',
 'farz',
 'fashion',
 'fateh',
 'fazilpuria',
 'fever',
 'firangi',
 'force',
 'force2',
 'francismenezes',
 'fraudsaiyaan',
 'fryday',
 'fuddu',
 'fugly',
 'fukreyreturns',
 'gabbarisback',
 'galbangayi',
 'gamepaisaladki',
 'gandharvsachdev',
 'gandhharvsachdeav',
 'gandhigiri',
 'ganeshchandanshive',
 'gangajumna',
 'gangofghosts',
 'gangster',
 'garammasala',
 'gardish',
 'gayatriiyer',
 'geetadutt',
 'geetsagar',
 'gehradaag',
 'genius',
 'ghaath',
 'ghajini',
 'ghar',
 'ghatak',
 'ghayalonceagain',
 'ghazab',
 'ghulam',
 'ghulamali',
 'ghunghat',
 'gippygrewal',
 'gold',
 'goliyonkirasleelaram',
 'golmaalagain',
 'goodboybadboy',
 'goodluck',
 'gopisunder',
 'goraaurkala',
 'goriterepyaarmein',
 'greatgrandmasti',
 'guestinlondon',
 'gulaabgang',
 'gullyboy',
 'gulrajsingh',
 'gulzar',
 'gumrah',
 'gunday',
 'gungajumna',
 'gunwantsen',
 'gupt',
 'gurdasmaan',
 'gurinderseagal',
 'guru',
 'gururandhawa',
 'haal',
 'haanmainebhipyaarkiya',
 'haathkisafai',
 'hadiqakiani',
 'haider',
 'halfgirlfriend',
 'hallabol',
 'hamariadhurikahani',
 'hameshaa',
 'hamsika',
 'hamsikaiyer',
 'hansrajhans',
 'happybhaagjayegi',
 'happyending',
 'happynewyear',
 'happyphirbhaagjayegi',
 'happyphirrbhaagjayegi',
 'hardiljopyarkarega',
 'hardkaur',
 'hardysandhu',
 'haricharan',
 'hariharan',
 'haripriya',
 'hariyaliaurrasta',
 'harrdysandhu',
 'harshdeepkaur',
 'harshitchouhan',
 'harshitsaxena',
 'haseenaparkar',
 'haseetohphasee',
 'hatestory2',
 'hatestory3',
 'hatestory4',
 'haunted',
 'heartless',
 'hebbuli',
 'hemantbrijwasi',
 'hemantkumar',
 'hemasardesai',
 'hemlata',
 'henna',
 'hero',
 'herohiralal',
 'heroine',
 'heropanti',
 'heyybaby',
 'heyybabyy',
 'hichki',
 'highjack',
 'himalaykigodmein',
 'himanikapoor',
 'himeshreshammiya',
 'himmataurmehanat',
 'himmatwala',
 'hindimedium',
 'hindustankikasam',
 'hiralbrahmbhatt',
 'hiteshsonik',
 'housefull',
 'housefull2',
 'housefull3',
 'hrishikeshkamerkar',
 'hrithikroshan',
 'humaapkehainkoun',
 'humapkehainkoun',
 'humdildechukesanam',
 'humhainrahipyaarke',
 'humhairahipyaarke',
 'humhindustani',
 'humkodeewanakargaye',
 'humptysharmakidulhania',
 'humsaath',
 'humsehaimuqabala',
 'humshakals',
 'humsubchorhain',
 'humtum',
 'humtumharehainsanam',
 'hussain',
 'idon',
 'ihateluvstory',
 'ihateluvstorys',
 'ikka',
 'ilaarun',
 'ilaiyaraaja',
 'ilovenewyear',
 'imaandaar',
 'imeaurmain',
 'imeaurmein',
 'imemain',
 'imrankhan',
 'indeepbakshi',
 'inderbawra',
 'inderjeet',
 'india',
 'indian',
 'indusarkar',
 'internationalvillager',
 'iqbal',
 'irada',
 'irfan',
 'irshadkamil',
 'irshanashraf',
 'iseeyou',
 'ishaan',
 'ishanmitra',
 'ishaqzaade',
 'ishers',
 'ishita',
 'ishkqinparis',
 'ishq',
 'ishqbector',
 'ishqclick',
 'ishqiya',
 'ishqtera',
 'ishqvishk',
 'ishwari',
 'ismaildarbar',
 'ittefaq',
 'iuliavantur',
 'jaan',
 'jaanetuyajaanena',
 'jaanterenaam',
 'jaanwar',
 'jaavedjaffrey',
 'jabharrymetsejal',
 'jabpyarkisisehotahai',
 'jabpyarkisisisehotahai',
 'jabtakhaijaan',
 'jabwemet',
 'jackpot',
 'jaggajasoos',
 'jagjitkaur',
 'jagjitsingh',
 'jagriti',
 'jaiho',
 'jalebi',
 'janaki',
 'janibaboo',
 'jannat',
 'jannat2',
 'jasbirjassi',
 'jasleenroyal',
 'jasminesandlas',
 'jasminwalia',
 'jaspeertsingh',
 'jaspindernarula',
 'jaspindernirula',
 'jaspreetsingh',
 'jassigill',
 'jaswindernarula',
 'jatin',
 'javedali',
 'javedbasheer',
 'javedbashir',
 'javedhussain',
 'jawanidiwani',
 'jayantabhaikiluvstory',
 'jayeshgandhi',
 'jayshreeshivram',
 'jazbaa',
 'jazdhami',
 'jazzyb',
 'jeet',
 'jeetgannguli',
 'jhukgayaaasman',
 'jiaaurjia',
 'jigar',
 'jigarsaraiya',
 'jisdeshmaingangarehtahai',
 'jisdeshmeingangabehtihai',
 'jisdeshmeingangarehtahai',
 'jisdeshmeinrehtahai',
 'jism',
 'jism2',
 'jodhaakbar',
 'jodibreakers',
 'johnabraham',
 'johnymeranaam',
 'joi',
 'joibarua',
 'jojeetawohisikander',
 'jojomukherjee',
 'joker',
 'jolly',
 'jollyllb2',
 'jollymukherjee',
 'jonitagandhi',
 'jordipatel',
 'jordypatel',
 'josh',
 'jubinnautiyal',
 'judaai',
 'judwaa2',
 'juggyd',
 'june',
 'junglee',
 'junooniyat',
 'jurm',
 'jyoticatangri',
 'jyotinooran',
 'ka',
 'kaabil',
 'kaajal',
 'kaalakaandi',
 'kaalia',
 'kaanchi',
 'kaante',
 'kabhialvidanaakehna',
 'kabhikabhie',
 'kabhikhushikabhiegham',
 'kabhinakabhi',
 'kachchedhaage',
 'kahaani2',
 'kahinpyaarnahojaye',
 'kahonaa',
 'kailashkher',
 'kalaakaar',
 'kalabazar',
 'kalhonaaho',
 'kalpana',
 'kalpanapatowary',
 'kaly',
 'kalyug',
 'kamaaldhamaalmalamaa',
 'kamaalkhan',
 'kamalbarot',
 'kamalhaasan',
 'kamalkhan',
 'kambakkhtishq',
 'kaminey',
 'kanchan',
 'kanhaiya',
 'kanikajoshi',
 'kanikakapoor',
 'kanyadaan',
 'kapoor',
 'karam',
 'karanarjun',
 'kareeb',
 'karma',
 'karsansagathia',
 'karsansangathia',
 'karthik',
 'karthikcallingkarthik',
 'karwaan',
 'karzzz',
 'karzzzz',
 'katipatang',
 'kaushikichakraborty',
 'kavipradeep',
 'kavitakrishnamurthy',
 'kavitaseth',
 'kedarnath',
 'keeravani',
 'keerthisagathia',
 'kgf',
 'khakee',
 'khalnayak',
 'khamoshiyan',
 'khattameetha',
 'kheleinhumjeejaansey',
 'kheltoabbshuruhoga',
 'khiladi',
 'khiladi786',
 'khiladiyonkakhiladi',
 'khilona',
 'khoobsurat',
 'khudagawah',
 'khuddar',
 'khullamkhullapyaarkaren',
 'khushboogrewal',
 'khushboojain',
 'khushhboogrewal',
 'khushi',
 'ki',
 'kick',
 'killdil',
 'kirtisagathia',
 'kishorekumar',
 'kishorigowariker',
 'kiskiskopyaarkaroon',
 'kismatkonnection',
 'kites',
 'kk',
 'kohinoor',
 'koiaapsa',
 'koimilgaya',
 'koyla',
 'kranti',
 'krantiveer',
 'krazzy4',
 'krishna',
 'krishnabeura',
 'krishnabeuraa',
 'krrish',
 'krrish3',
 'kshitijtarey',
 'kuchhbheegealfaaz',
 'kuchkuchhotahai',
 'kuchkuchlochahai',
 'kumarsanu',
 'kunal',
 'kunalganjawala',
 'kunalpandit',
 'kurbaan',
 'kurukshetra',
 'kyaakoolhainhum3',
 'kyakehna',
 'laadla',
 'laalikishaadimeinlaaddoodeewana',
 'laawaris',
 'labhjanjua',
 'ladiesvsrickybahl',
 'lagaan',
 'lagerahomunnabhai',
 'lahookedorang',
 'lailamajnu',
 'lakshay',
 'lakshmi',
 'lakshya',
 'lalit',
 'lamhe',
 'latamangeshkar',
 'leela',
 'lehmberhussainpuri',
 'lifeinametro',
 'lifeisbeautiful',
 'lilgolu',
 'londondreams',
 'lootera',
 'lottery',
 'love',
 'loveaajkal',
 'loveajkal',
 'lovebreakupszindagi',
 'loveinshimla',
 'lovekatheend',
 'loveratri',
 'loveshhuda',
 'loymendonsa',
 'luck',
 'luckbychance',
 'lucknowcentral',
 'lucky',
 'luckyali',
 'lukachuppi',
 'luvkatheend',
 'luvshvpyarvyar',
 'machine',
 'madhoshi',
 'madhumati',
 'madhuridixit',
 'madhushree',
 'madrascafe',
 'mahadevan',
 'mahalakshmi',
 'mahalakshmiiyer',
 'mahalaxmi',
 'mahalaxmiiyer',
 'mahathi',
 'mahendrakapoor',
 'mahuakamat',
 'mainaisahihoon',
 'mainaurcharles',
 'mainediltujhkodiya',
 'mainepyarkiya',
 'mainhoonna',
 'mainkhiladituanari',
 'mainpremkidiwanihoon',
 'mainterahero',
 'malhar',
 'malkitsingh',
 'mamtasharma',
 'manak',
 'manasi',
 'manharudhas',
 'manishkumartipu',
 'manjmusik',
 'manmarziyaan',
 'manmohanwaris',
 'mann',
 'mannadey',
 'mannatnoor',
 'manoharshetty',
 'manojmishra',
 'manpreetakhtar',
 'mansheelgujral',
 'manto',
 'marianne',
 'marianned',
 'marykom',
 'mashaal',
 'masoom',
 'mastersaleem',
 'matrukibijleekamandola',
 'mausam',
 'mawaali',
 'meenaljain',
 'meetbros',
 'meetbrosanjjan',
 'meghasriramdalton',
 'meghnamishra',
 'mehrunisavlubu',
 'mello',
 'mellowd',
 'menatwork',
 'meranaamjoker',
 'merchant',
 'merebrotherkidulhan',
 'meredadkimaruti',
 'meredostpictureabhibakihai',
 'meremehboob',
 'meresanam',
 'meripyaaribindu',
 'merriene',
 'mika',
 'mikasingh',
 'mikhasingh',
 'milan',
 'milengemilenge',
 'milinair',
 'millindgaba',
 'mirayavarma',
 'mirzya',
 'missionkashmir',
 'misspooja',
 'mithoon',
 'mitron',
 'mohabbatein',
 'mohammadaziz',
 'mohammadsayeed',
 'mohammed',
 'mohammedaslam',
 'mohammedaziz',
 'mohammedirfan',
 'mohammedrafi',
 'mohan',
 'mohankanan',
 'mohd',
 'mohdvakil',
 'mohenjodaro',
 'mohitchauhan',
 'mohitchuahaan',
 'mohra',
 'moinuddinmanchala',
 'monalithakur',
 'moneyhaitohhoneyhai',
 'monicadogra',
 'monsoonshootout',
 'mr',
 ...]

In [33]:
len(cv.get_feature_names())

1697

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [35]:
similarity.shape

(2406, 2406)

In [36]:
similarity

array([[1.        , 0.2236068 , 0.25819889, ..., 0.25819889, 0.25819889,
        0.        ],
       [0.2236068 , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.25819889, 0.        , 1.        , ..., 0.33333333, 0.33333333,
        0.        ],
       ...,
       [0.25819889, 0.        , 0.33333333, ..., 1.        , 0.66666667,
        0.        ],
       [0.25819889, 0.        , 0.33333333, ..., 0.66666667, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [37]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x : x[1])[1:6]

[(5, 0.5163977794943223),
 (34, 0.5163977794943223),
 (183, 0.5163977794943223),
 (270, 0.5163977794943223),
 (372, 0.5163977794943223)]

In [38]:
def recommend(song):
    song_index = new_df.loc[new_df['song'] == song].index[0]
    distances = similarity[song_index]
    songs_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x : x[1])[1:11]
    
    for i in songs_list:
        print(new_df.loc[i[0], 'song'])

In [106]:
recommend('Lag Ja Gale')

Aap Ki Nazron Ne Samjha
Tera Mera Pyar Amar
Mere Khwabon Mein
Meri Bindiya Teri Nindiya
Kaise Piya Se
Mora Gora Ang Laile
Kashmir Ki Kali Hoon Main
Dagabaaz Tori Batiyan
Dhoondo Dhoondo Re Sajna
Mehboob Mere Mehboob Mere

In [40]:
import pickle

pickle.dump(new_df, open('songs_recommender.pkl', 'wb'))